# Generated by Django 5.2 on 2025-04-23 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10-11 chữ số', regex='^0\\d{9,10}$')])),
                ('dia_chi', models.CharField(max_length=255)),
                ('loai_nguoi_dung', models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
