# Generated by Django 5.2 on 2025-04-23 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanChoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khu_vuc', models.CharField(max_length=100)),
                ('dia_diem', models.CharField(max_length=255)),
                ('gio_mo_cua', models.TimeField()),
                ('gio_dong_cua', models.TimeField()),
                ('gia_thue_theo_gio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Giá thuê phải lớn hơn 0')])),
                ('mo_ta', models.TextField()),
                ('so_san_con', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Số sân phải lớn hơn 0')])),
            ],
        ),
    ]
