# Generated by Django 5.2 on 2025-04-23 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_so', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Điểm số phải từ 1 đến 5'), django.core.validators.MaxValueValidator(5, message='Điểm số phải từ 1 đến 5')])),
                ('nhan_xet', models.TextField()),
                ('ngay_danh_gia', models.DateField(auto_now_add=True)),
                ('khu_vuc_san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.sanchoi')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('khu_vuc_san', 'nguoi_dung')},
            },
        ),
    ]
