# Generated by Django 5.2 on 2025-04-23 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomChoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('thoi_gian_hoat_dong', models.CharField(max_length=100)),
                ('dia_diem_hoat_dong', models.CharField(max_length=255)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhVienNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tham_gia', models.DateField(auto_now_add=True)),
                ('nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.nhomchoi')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nhom', 'thanh_vien')},
            },
        ),
    ]
