# Generated by Django 5.2 on 2025-06-05 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10-11 chữ số', regex='^0\\d{9,10}$')])),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=10, null=True)),
                ('vai_tro', models.CharField(choices=[('nguoi_dung', 'Người dùng'), ('admin', 'Quản trị viên')], default='nguoi_dung', max_length=20)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
