# Generated by Django 5.2 on 2025-06-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(default='nguoi_dung', max_length=20),
        ),
    ]
