# Generated by Django 5.2 on 2025-06-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0002_alter_nguoidung_vai_tro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='user',
        ),
    ]
