# Generated by Django 5.2 on 2025-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0003_remove_nguoidung_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san', models.CharField(max_length=100)),
                ('dia_diem', models.CharField(max_length=255)),
                ('gia_thue_theo_gio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('so_san_con', models.PositiveIntegerField()),
                ('gio_mo_cua', models.TimeField()),
                ('gio_dong_cua', models.TimeField()),
            ],
        ),
    ]
