# Generated by Django 5.2 on 2025-06-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0005_rename_court_san_danhgiasan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgiasan',
            old_name='nguoi_dung',
            new_name='nguoi_dung_id',
        ),
        migrations.RenameField(
            model_name='danhgiasan',
            old_name='san',
            new_name='san_id',
        ),
    ]
