# Generated by Django 5.2 on 2025-06-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0006_rename_nguoi_dung_danhgiasan_nguoi_dung_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('noi_dung', models.TextField()),
                ('cap_do', models.CharField(blank=True, choices=[('de', 'Dễ'), ('trung binh', 'Trung bình'), ('kho', 'Khó')], max_length=20, null=True)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huong_dans', to='pickleball_platform_management.nguoidung')),
            ],
        ),
    ]
