# Generated by Django 5.2 on 2025-06-09 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0007_huongdan'),
    ]

    operations = [
        migrations.AddField(
            model_name='san',
            name='doanh_thu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='danhgiasan',
            name='noi_dung',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='huongdan',
            name='tieu_de',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10-11 chữ số', regex='^0\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='san',
            name='dia_diem',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_dat', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_bat_dau', models.TimeField()),
                ('thoi_gian_ket_thuc', models.TimeField()),
                ('so_luong_san', models.PositiveIntegerField()),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nguoi_dung_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_sans', to='pickleball_platform_management.nguoidung')),
                ('san_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_sans', to='pickleball_platform_management.san')),
            ],
        ),
    ]
