# Generated by Django 5.2 on 2025-06-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0009_alter_nguoidung_so_dien_thoai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='san',
            old_name='dia_diem',
            new_name='dia_chi',
        ),
    ]
