# Generated by Django 5.2 on 2025-06-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball_platform_management', '0010_rename_dia_diem_san_dia_chi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='san',
            old_name='dia_chi',
            new_name='dia_chi_cu_the',
        ),
    ]
